### ISSUE TITLE
docker-api gem pinned in metadata.rb does not match latest Chef binaries

### ISSUE THREAD

**Issue by bkonick** [sous-chefs/docker#1135]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

The docker-api gem in metadata.rb is set to `~> 1.34.0` but Chef Workstation appears to include `2.0.0`. This results in a warning in ChefSpec. I have not yet observed a hard failure in our wrapper. Directly running in this cookbook repo results in hard failures (unsure if those are pre-existing).

## :pancakes: Cookbook version

6.0.3

## :woman_cook:  Chef-Infra Version

```
Chef Workstation version: 20.9.158
Chef Infra Client version: 16.5.77
Chef InSpec version: 4.23.11
Chef CLI version: 3.0.32
Chef Habitat version: 1.6.56
Test Kitchen version: 2.7.2
Cookstyle version: 6.19.5
```

## :tophat: Platform details

Occurs on my workstation (macOS 10.15.7) and the docker image for Chef Workstation 20.9.158 that we use in our pipeline.

## Steps To Reproduce

1. Include the docker cookbook in a wrapper or run `chef exec rspec` directly in this cookbook repo
2. Run `chef exec rspec`

## :police_car: Expected behavior

A version constraint that matches what is shipped with Chef binaries

## :heavy_plus_sign: Additional context

Error message details from our wrapper:
```
$ chef exec rspec
/opt/chef-workstation/embedded/bin/ruby -I/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/rspec-support-3.9.3/lib:/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb --fail-fast
No matching version found for 'docker-api' in your gem environment.
 - if you are using Chef Workstation, run the following command: "chef gem install docker-api --version '~> 1.34.0'"
 - if you are using bundler, append "gem 'docker-api', '~> 1.34.0'" to your Gemfile and run "bundle install"
 - otherwise run: "gem install docker-api --version '~> 1.34.0'"
```

Error message details directly from this cookbook repo:
```
$ chef exec rspec
/opt/chef-workstation/embedded/lib/ruby/2.7.0/net/http/exceptions.rb:25: warning: already initialized constant Net::HTTPClientException
/opt/chef-workstation/embedded/lib/ruby/2.7.0/net/http.rb:388: warning: previous definition of HTTPClientException was here
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}
No matching version found for 'docker-api' in your gem environment.
 - if you are using Chef Workstation, run the following command: "chef gem install docker-api --version '~> 1.34.0'"
 - if you are using bundler, append "gem 'docker-api', '~> 1.34.0'" to your Gemfile and run "bundle install"
 - otherwise run: "gem install docker-api --version '~> 1.34.0'"
.............................................................................................................No matching version found for 'docker-api' in your gem environment.
 - if you are using Chef Workstation, run the following command: "chef gem install docker-api --version '~> 1.34.0'"
 - if you are using bundler, append "gem 'docker-api', '~> 1.34.0'" to your Gemfile and run "bundle install"
 - otherwise run: "gem install docker-api --version '~> 1.34.0'"
.......No matching version found for 'docker-api' in your gem environment.
 - if you are using Chef Workstation, run the following command: "chef gem install docker-api --version '~> 1.34.0'"
 - if you are using bundler, append "gem 'docker-api', '~> 1.34.0'" to your Gemfile and run "bundle install"
 - otherwise run: "gem install docker-api --version '~> 1.34.0'"
..No matching version found for 'docker-api' in your gem environment.
 - if you are using Chef Workstation, run the following command: "chef gem install docker-api --version '~> 1.34.0'"
 - if you are using bundler, append "gem 'docker-api', '~> 1.34.0'" to your Gemfile and run "bundle install"
 - otherwise run: "gem install docker-api --version '~> 1.34.0'"
....F................................No matching version found for 'docker-api' in your gem environment.
 - if you are using Chef Workstation, run the following command: "chef gem install docker-api --version '~> 1.34.0'"
 - if you are using bundler, append "gem 'docker-api', '~> 1.34.0'" to your Gemfile and run "bundle install"
 - otherwise run: "gem install docker-api --version '~> 1.34.0'"
.No matching version found for 'docker-api' in your gem environment.
 - if you are using Chef Workstation, run the following command: "chef gem install docker-api --version '~> 1.34.0'"
 - if you are using bundler, append "gem 'docker-api', '~> 1.34.0'" to your Gemfile and run "bundle install"
 - otherwise run: "gem install docker-api --version '~> 1.34.0'"
.....No matching version found for 'docker-api' in your gem environment.
 - if you are using Chef Workstation, run the following command: "chef gem install docker-api --version '~> 1.34.0'"
 - if you are using bundler, append "gem 'docker-api', '~> 1.34.0'" to your Gemfile and run "bundle install"
 - otherwise run: "gem install docker-api --version '~> 1.34.0'"
......No matching version found for 'docker-api' in your gem environment.
 - if you are using Chef Workstation, run the following command: "chef gem install docker-api --version '~> 1.34.0'"
 - if you are using bundler, append "gem 'docker-api', '~> 1.34.0'" to your Gemfile and run "bundle install"
 - otherwise run: "gem install docker-api --version '~> 1.34.0'"
............No matching version found for 'docker-api' in your gem environment.
 - if you are using Chef Workstation, run the following command: "chef gem install docker-api --version '~> 1.34.0'"
 - if you are using bundler, append "gem 'docker-api', '~> 1.34.0'" to your Gemfile and run "bundle install"
 - otherwise run: "gem install docker-api --version '~> 1.34.0'"
...........No matching version found for 'docker-api' in your gem environment.
 - if you are using Chef Workstation, run the following command: "chef gem install docker-api --version '~> 1.34.0'"
 - if you are using bundler, append "gem 'docker-api', '~> 1.34.0'" to your Gemfile and run "bundle install"
 - otherwise run: "gem install docker-api --version '~> 1.34.0'"
....No matching version found for 'docker-api' in your gem environment.
 - if you are using Chef Workstation, run the following command: "chef gem install docker-api --version '~> 1.34.0'"
 - if you are using bundler, append "gem 'docker-api', '~> 1.34.0'" to your Gemfile and run "bundle install"
 - otherwise run: "gem install docker-api --version '~> 1.34.0'"
.............................No matching version found for 'docker-api' in your gem environment.
 - if you are using Chef Workstation, run the following command: "chef gem install docker-api --version '~> 1.34.0'"
 - if you are using bundler, append "gem 'docker-api', '~> 1.34.0'" to your Gemfile and run "bundle install"
 - otherwise run: "gem install docker-api --version '~> 1.34.0'"
........No matching version found for 'docker-api' in your gem environment.
 - if you are using Chef Workstation, run the following command: "chef gem install docker-api --version '~> 1.34.0'"
 - if you are using bundler, append "gem 'docker-api', '~> 1.34.0'" to your Gemfile and run "bundle install"
 - otherwise run: "gem install docker-api --version '~> 1.34.0'"
....................No matching version found for 'docker-api' in your gem environment.
 - if you are using Chef Workstation, run the following command: "chef gem install docker-api --version '~> 1.34.0'"
 - if you are using bundler, append "gem 'docker-api', '~> 1.34.0'" to your Gemfile and run "bundle install"
 - otherwise run: "gem install docker-api --version '~> 1.34.0'"
.No matching version found for 'docker-api' in your gem environment.
 - if you are using Chef Workstation, run the following command: "chef gem install docker-api --version '~> 1.34.0'"
 - if you are using bundler, append "gem 'docker-api', '~> 1.34.0'" to your Gemfile and run "bundle install"
 - otherwise run: "gem install docker-api --version '~> 1.34.0'"
...........No matching version found for 'docker-api' in your gem environment.
 - if you are using Chef Workstation, run the following command: "chef gem install docker-api --version '~> 1.34.0'"
 - if you are using bundler, append "gem 'docker-api', '~> 1.34.0'" to your Gemfile and run "bundle install"
 - otherwise run: "gem install docker-api --version '~> 1.34.0'"
No matching version found for 'docker-api' in your gem environment.
 - if you are using Chef Workstation, run the following command: "chef gem install docker-api --version '~> 1.34.0'"
 - if you are using bundler, append "gem 'docker-api', '~> 1.34.0'" to your Gemfile and run "bundle install"
 - otherwise run: "gem install docker-api --version '~> 1.34.0'"
FNo matching version found for 'docker-api' in your gem environment.
 - if you are using Chef Workstation, run the following command: "chef gem install docker-api --version '~> 1.34.0'"
 - if you are using bundler, append "gem 'docker-api', '~> 1.34.0'" to your Gemfile and run "bundle install"
 - otherwise run: "gem install docker-api --version '~> 1.34.0'"
No matching version found for 'docker-api' in your gem environment.
 - if you are using Chef Workstation, run the following command: "chef gem install docker-api --version '~> 1.34.0'"
 - if you are using bundler, append "gem 'docker-api', '~> 1.34.0'" to your Gemfile and run "bundle install"
 - otherwise run: "gem install docker-api --version '~> 1.34.0'"
FNo matching version found for 'docker-api' in your gem environment.
 - if you are using Chef Workstation, run the following command: "chef gem install docker-api --version '~> 1.34.0'"
 - if you are using bundler, append "gem 'docker-api', '~> 1.34.0'" to your Gemfile and run "bundle install"
 - otherwise run: "gem install docker-api --version '~> 1.34.0'"
No matching version found for 'docker-api' in your gem environment.
 - if you are using Chef Workstation, run the following command: "chef gem install docker-api --version '~> 1.34.0'"
 - if you are using bundler, append "gem 'docker-api', '~> 1.34.0'" to your Gemfile and run "bundle install"
 - otherwise run: "gem install docker-api --version '~> 1.34.0'"
F..No matching version found for 'docker-api' in your gem environment.
 - if you are using Chef Workstation, run the following command: "chef gem install docker-api --version '~> 1.34.0'"
 - if you are using bundler, append "gem 'docker-api', '~> 1.34.0'" to your Gemfile and run "bundle install"
 - otherwise run: "gem install docker-api --version '~> 1.34.0'"
No matching version found for 'docker-api' in your gem environment.
 - if you are using Chef Workstation, run the following command: "chef gem install docker-api --version '~> 1.34.0'"
 - if you are using bundler, append "gem 'docker-api', '~> 1.34.0'" to your Gemfile and run "bundle install"
 - otherwise run: "gem install docker-api --version '~> 1.34.0'"
FNo matching version found for 'docker-api' in your gem environment.
 - if you are using Chef Workstation, run the following command: "chef gem install docker-api --version '~> 1.34.0'"
 - if you are using bundler, append "gem 'docker-api', '~> 1.34.0'" to your Gemfile and run "bundle install"
 - otherwise run: "gem install docker-api --version '~> 1.34.0'"
No matching version found for 'docker-api' in your gem environment.
 - if you are using Chef Workstation, run the following command: "chef gem install docker-api --version '~> 1.34.0'"
 - if you are using bundler, append "gem 'docker-api', '~> 1.34.0'" to your Gemfile and run "bundle install"
 - otherwise run: "gem install docker-api --version '~> 1.34.0'"
FNo matching version found for 'docker-api' in your gem environment.
 - if you are using Chef Workstation, run the following command: "chef gem install docker-api --version '~> 1.34.0'"
 - if you are using bundler, append "gem 'docker-api', '~> 1.34.0'" to your Gemfile and run "bundle install"
 - otherwise run: "gem install docker-api --version '~> 1.34.0'"
No matching version found for 'docker-api' in your gem environment.
 - if you are using Chef Workstation, run the following command: "chef gem install docker-api --version '~> 1.34.0'"
 - if you are using bundler, append "gem 'docker-api', '~> 1.34.0'" to your Gemfile and run "bundle install"
 - otherwise run: "gem install docker-api --version '~> 1.34.0'"
F

Failures:

  1) docker_test::image testing specifying a tag and read/write timeouts pulls docker_image[alpine]
     Failure/Error:
       expect(chef_run).to pull_docker_image('alpine').with(
         tag: '3.1',
         read_timeout: 60,
         write_timeout: 60
       )

       expected "docker_image[alpine-localhost]" to have parameters:

         tag "3.1", was "2.7"
         read_timeout 60, was 120
         write_timeout 60, was nil
     # ./spec/docker_test/image_spec.rb:59:in `block (3 levels) in <top (required)>'

  2) docker_container creates a docker container with default options is expected not to raise Exception
     Failure/Error: expect { chef_run }.to_not raise_error

       expected no Exception, got #<Excon::Error::StubNotFound: docker_container[hello_world] (docker::_test line 66) had an error: Exc...  :versions            => "excon/0.76.0 (x86_64-darwin17) ruby/2.7.1"
         :write_timeout       => 60
       > with backtrace:
         # /var/folders/66/cvjlrzpn61x20c3cwrq72pv40000gp/T/d20201007-3299-h301r4/cookbooks/docker/libraries/docker_container.rb:402:in `block (2 levels) in <class:DockerContainer>'
         # /var/folders/66/cvjlrzpn61x20c3cwrq72pv40000gp/T/d20201007-3299-h301r4/cookbooks/docker/libraries/docker_base.rb:29:in `with_retries'
         # /var/folders/66/cvjlrzpn61x20c3cwrq72pv40000gp/T/d20201007-3299-h301r4/cookbooks/docker/libraries/docker_container.rb:402:in `block in <class:DockerContainer>'
         # ./spec/libraries/container_spec.rb:73:in `block (4 levels) in <top (required)>'
         # ./spec/libraries/container_spec.rb:73:in `block (3 levels) in <top (required)>'
     # ./spec/libraries/container_spec.rb:73:in `block (3 levels) in <top (required)>'

  3) docker_container creates a docker container with healthcheck options is expected not to raise Exception
     Failure/Error: expect { chef_run }.to_not raise_error

       expected no Exception, got #<Excon::Error::StubNotFound: docker_container[hello_world] (docker::_test line 83) had an error: Exc...  :versions            => "excon/0.76.0 (x86_64-darwin17) ruby/2.7.1"
         :write_timeout       => 60
       > with backtrace:
         # /var/folders/66/cvjlrzpn61x20c3cwrq72pv40000gp/T/d20201007-3299-h301r4/cookbooks/docker/libraries/docker_container.rb:402:in `block (2 levels) in <class:DockerContainer>'
         # /var/folders/66/cvjlrzpn61x20c3cwrq72pv40000gp/T/d20201007-3299-h301r4/cookbooks/docker/libraries/docker_base.rb:29:in `with_retries'
         # /var/folders/66/cvjlrzpn61x20c3cwrq72pv40000gp/T/d20201007-3299-h301r4/cookbooks/docker/libraries/docker_container.rb:402:in `block in <class:DockerContainer>'
         # ./spec/libraries/container_spec.rb:100:in `block (4 levels) in <top (required)>'
         # ./spec/libraries/container_spec.rb:100:in `block (3 levels) in <top (required)>'
     # ./spec/libraries/container_spec.rb:100:in `block (3 levels) in <top (required)>'

  4) docker_container creates a docker container with default options for windows is expected not to raise Exception
     Failure/Error: expect { chef_run }.to_not raise_error

       expected no Exception, got #<Excon::Error::StubNotFound: docker_container[hello_world] (docker::_test line 111) had an error: Ex...  :versions            => "excon/0.76.0 (x86_64-darwin17) ruby/2.7.1"
         :write_timeout       => 60
       > with backtrace:
         # /var/folders/66/cvjlrzpn61x20c3cwrq72pv40000gp/T/d20201007-3299-h301r4/cookbooks/docker/libraries/docker_container.rb:402:in `block (2 levels) in <class:DockerContainer>'
         # /var/folders/66/cvjlrzpn61x20c3cwrq72pv40000gp/T/d20201007-3299-h301r4/cookbooks/docker/libraries/docker_base.rb:29:in `with_retries'
         # /var/folders/66/cvjlrzpn61x20c3cwrq72pv40000gp/T/d20201007-3299-h301r4/cookbooks/docker/libraries/docker_container.rb:402:in `block in <class:DockerContainer>'
         # ./spec/libraries/container_spec.rb:118:in `block (4 levels) in <top (required)>'
         # ./spec/libraries/container_spec.rb:118:in `block (3 levels) in <top (required)>'
     # ./spec/libraries/container_spec.rb:118:in `block (3 levels) in <top (required)>'

  5) docker_registry logs into a docker registry with default options is expected not to raise Exception
     Failure/Error: expect { chef_run }.to_not raise_error

       expected no Exception, got #<Excon::Error::StubNotFound: docker_registry[chefspec_custom_registry] (docker::_test line 30) had a...  :versions            => "excon/0.76.0 (x86_64-darwin17) ruby/2.7.1"
         :write_timeout       => 60
       > with backtrace:
         # /var/folders/66/cvjlrzpn61x20c3cwrq72pv40000gp/T/d20201007-3299-h301r4/cookbooks/docker/libraries/docker_registry.rb:31:in `block in <class:DockerRegistry>'
         # (eval):2:in `block in action_login'
         # (eval):2:in `action_login'
         # ./spec/libraries/registry_spec.rb:37:in `block (4 levels) in <top (required)>'
         # ./spec/libraries/registry_spec.rb:37:in `block (3 levels) in <top (required)>'
     # ./spec/libraries/registry_spec.rb:37:in `block (3 levels) in <top (required)>'

  6) docker_registry logs into a docker registry with host is expected not to raise Exception
     Failure/Error: expect { chef_run }.to_not raise_error

       expected no Exception, got #<Excon::Error::StubNotFound: docker_registry[chefspec_custom_registry] (docker::_test line 49) had a...  :versions            => "excon/0.76.0 (x86_64-darwin17) ruby/2.7.1"
         :write_timeout       => 60
       > with backtrace:
         # /var/folders/66/cvjlrzpn61x20c3cwrq72pv40000gp/T/d20201007-3299-h301r4/cookbooks/docker/libraries/docker_registry.rb:31:in `block in <class:DockerRegistry>'
         # (eval):2:in `block in action_login'
         # (eval):2:in `action_login'
         # ./spec/libraries/registry_spec.rb:57:in `block (4 levels) in <top (required)>'
         # ./spec/libraries/registry_spec.rb:57:in `block (3 levels) in <top (required)>'
     # ./spec/libraries/registry_spec.rb:57:in `block (3 levels) in <top (required)>'

  7) docker_registry logs into a docker registry with host environment variable is expected not to raise Exception
     Failure/Error: expect { chef_run }.to_not raise_error

       expected no Exception, got #<Excon::Error::StubNotFound: docker_registry[chefspec_custom_registry] (docker::_test line 69) had a...  :versions            => "excon/0.76.0 (x86_64-darwin17) ruby/2.7.1"
         :write_timeout       => 60
       > with backtrace:
         # /var/folders/66/cvjlrzpn61x20c3cwrq72pv40000gp/T/d20201007-3299-h301r4/cookbooks/docker/libraries/docker_registry.rb:31:in `block in <class:DockerRegistry>'
         # (eval):2:in `block in action_login'
         # (eval):2:in `action_login'
         # ./spec/libraries/registry_spec.rb:79:in `block (4 levels) in <top (required)>'
         # ./spec/libraries/registry_spec.rb:79:in `block (3 levels) in <top (required)>'
     # ./spec/libraries/registry_spec.rb:79:in `block (3 levels) in <top (required)>'

Finished in 6.19 seconds (files took 1.44 seconds to load)
271 examples, 7 failures

Failed examples:

rspec ./spec/docker_test/image_spec.rb:58 # docker_test::image testing specifying a tag and read/write timeouts pulls docker_image[alpine]
rspec ./spec/libraries/container_spec.rb:72 # docker_container creates a docker container with default options is expected not to raise Exception
rspec ./spec/libraries/container_spec.rb:99 # docker_container creates a docker container with healthcheck options is expected not to raise Exception
rspec ./spec/libraries/container_spec.rb:117 # docker_container creates a docker container with default options for windows is expected not to raise Exception
rspec ./spec/libraries/registry_spec.rb:36 # docker_registry logs into a docker registry with default options is expected not to raise Exception
rspec ./spec/libraries/registry_spec.rb:56 # docker_registry logs into a docker registry with host is expected not to raise Exception
rspec ./spec/libraries/registry_spec.rb:75 # docker_registry logs into a docker registry with host environment variable is expected not to raise Exception
```

Questions:
* Should this cookbook be installing this version of the gem?
* Should the dependency be adjusted to accommodate newer version of Chef Workstation?
* Should the dependency even be listed in metadata.rb?

**Comment by dheerajd-msys** [comment]
@antima-gupta Please check this ^
