### ISSUE TITLE
Error executing action `run` on resource 'docker_exec[default]'

### ISSUE THREAD

**Issue by ramereth** [sous-chefs/docker#1137]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

Running `docker_exec 'default'` results in the following error:
```
  * docker_exec[default] action run
    
    ================================================================================
    Error executing action `run` on resource 'docker_exec[default]'
    ================================================================================
    
    TypeError
    ---------
    no implicit conversion of String into Integer
    
    Cookbook Trace: (most recent call first)
    ----------------------------------------
    /opt/kitchen/cache/cookbooks/docker/libraries/docker_exec.rb:18:in `block (3 levels) in <class:DockerExec>'
    /opt/kitchen/cache/cookbooks/docker/libraries/docker_base.rb:29:in `with_retries'
    /opt/kitchen/cache/cookbooks/docker/libraries/docker_exec.rb:18:in `block (2 levels) in <class:DockerExec>'
    /opt/kitchen/cache/cookbooks/docker/libraries/docker_exec.rb:17:in `block in <class:DockerExec>'
    
    Resource Declaration:
    ---------------------
    # In /opt/kitchen/cache/cookbooks/docker_test/recipes/exec.rb
    
     27: docker_exec 'default'
    
    Compiled Resource:
    ------------------
    # Declared in /opt/kitchen/cache/cookbooks/docker_test/recipes/exec.rb:27:in `from_file'
    
    docker_exec("default") do
      action [:run]
      default_guard_interpreter :default
      declared_type :docker_exec
      cookbook_name "docker_test"
      recipe_name "exec"
      connection #<Docker::Connection:0x0000000005442d20 @url="unix:///", @options={:socket=>"/var/run/docker.sock", :read_timeout=>60}>
    end
    
    System Info:
    ------------
    chef_version=16.5.77
    platform=debian
    platform_version=9
    ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
    program_name=/opt/chef/bin/chef-client
    executable=/opt/chef/bin/chef-client
```

## :pancakes: Cookbook version

Version of the cookbook where you are encountering the issue.

## :woman_cook:  Chef-Infra Version

Version of chef-client in your environment.

## :tophat: Platform details

Operating system distribution and release version. Cloud provider if running in the cloud.

## :heavy_plus_sign: Additional context

Add any other context about the problem here. e.g. related issues or existing pull requests.

**Comment by damacus** [comment]
Should be fixed given the test suite exercise this resource in this way.
