### ISSUE TITLE
Issue with credentials on image pull

### ISSUE THREAD

**Issue by rmoriz** [sous-chefs/docker#1142]
## :ghost: Brief Description

bug in credentials handling in the following case:

- configured, working account for index.docker.io
- access to anonymous public registry, e.g. docker.elastic.co

## :pancakes: Cookbook version

master/head

## :woman_cook:  Chef-Infra Version

16.1.16

## Steps To Reproduce

source: https://github.com/sous-chefs/docker/blob/master/libraries/docker_image.rb#L184

```
docker_registry "https://index.docker.io/v1/" do
   username "user"
   password "password"
end

docker_image 'docker.elastic.co/elasticsearch/elasticsearch' do
  tag "7.9.3"
  action :pull
end
```

error:

```
 
    docker_image("docker.elastic.co/elasticsearch/elasticsearch") do
      action [:pull]
      default_guard_interpreter :default
      declared_type :docker_image
      cookbook_name "rmoriz-docker"
      recipe_name "rmoriz-test"
      tag "7.9.3"
      repo "docker.elastic.co/elasticsearch/elasticsearch"
      connection #<Docker::Connection:0x000055f24145c9d0 @url="unix:///", @options={:socket=>"/var/run/docker.sock", :read_timeout=>120}>
    end
    
    System Info:
    ------------
    chef_version=16.1.16
    platform=debian
    platform_version=10
    ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
    program_name=/opt/cinc/bin/cinc-client
    executable=/opt/cinc/bin/cinc-client

```

stacktrace:

```
Generated at 2020-11-19 16:03:55 +0000
Docker::Error::ServerError: docker_image[docker.elastic.co/elasticsearch/elasticsearch] (rmoriz-docker::rmoriz-test line 6) had an error: Docker::Error::ServerError: {"message":"Get https://docker.elastic.co/v2/elasticsearch/elasticsearch/manifests/7.9.3: unauthorized: authentication required"}
/opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/docker-api-2.0.0/lib/docker/connection.rb:50:in `rescue in request'
/opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/docker-api-2.0.0/lib/docker/connection.rb:37:in `request'
/opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/docker-api-2.0.0/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
/opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/docker-api-2.0.0/lib/docker/image.rb:114:in `create'
/var/cinc/cache/cookbooks/docker/libraries/docker_image.rb:151:in `block in pull_image'
/var/cinc/cache/cookbooks/docker/libraries/docker_base.rb:29:in `with_retries'
/opt/cinc/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `with_retries'
/var/cinc/cache/cookbooks/docker/libraries/docker_image.rb:148:in `pull_image'
/var/cinc/cache/cookbooks/docker/libraries/docker_image.rb:52:in `block in <class:DockerImage>'
(eval):2:in `block in action_pull'
/opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/provider.rb:279:in `instance_eval'
/opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/provider.rb:279:in `compile_and_converge_action'
(eval):2:in `action_pull'
/opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/provider.rb:220:in `run_action'
/opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/resource.rb:591:in `run_action'
/opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/runner.rb:74:in `run_action'
/opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/runner.rb:108:in `each'
/opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/runner.rb:108:in `run_all_actions'
/opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/runner.rb:132:in `block in converge'
/opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
/opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/resource_collection/stepable_iterator.rb:115:in `call_iterator_block'
/opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/resource_collection/stepable_iterator.rb:86:in `step'
/opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
/opt/cinc/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `execute_each_resource'
/opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/runner.rb:130:in `converge'
/opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/client.rb:714:in `block in converge'
/opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/client.rb:709:in `catch'
/opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/client.rb:709:in `converge'
/opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/client.rb:733:in `converge_and_save'
/opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/client.rb:288:in `run'
/opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/application.rb:292:in `run_with_graceful_exit_option'
/opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/application.rb:268:in `block in run_chef_client'
/opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/application.rb:251:in `run_chef_client'
/opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/application/base.rb:335:in `run_application'
/opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/application.rb:68:in `run'
/opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.1.16/bin/cinc-client:25:in `<top (required)>'
/opt/cinc/bin/cinc-client:171:in `load'
/opt/cinc/bin/cinc-client:171:in `<main>'

>>>> Caused by Excon::Error::InternalServerError: Expected([200, 201, 202, 203, 204, 301, 304]) <=> Actual(500 InternalServerError)

```

As far as I understand, `docker_image` defaults in https://github.com/sous-chefs/docker/blob/master/libraries/docker_image.rb#L184 to the docker.io credentials when no more specific credentials could be found. When accessing a public accessible registry with wrong credentials, this leads to the error mentioned above:

```ruby
(node.run_state['docker_auth'] ||= {})['index.docker.io']
```

**Comment by rmoriz** [comment]
Workaround seems to be to make sure the public registry is configured with empty properties:

```ruby
docker_registry "docker.elastic.co"
```

**Comment by ramereth** [comment]
@rmoriz what's the full workaround and/or the fix we need to make in the cookbook?

**Comment by rmoriz** [comment]
I'll provide a PR tomorrow
